import turtle
monty = turtle.Turtle()
monty.shape("turtle")
monty.penup()
monty.forward(100)
monty.write("Latający")
monty.right(144)
monty.forward(100)
monty.write("Żłów")
monty.right(144)
monty.forward(100)
monty.right(144)
monty.forward(100)
monty.write("Monty")
monty.right(144)
monty.forward(100)
monty.write("Pythona")
monty.right(144)
