import turtle
monty = turtle.Turtle()
monty.shape("turtle")
monty.color('blue')
monty.fillcolor('blue')
monty.begin_fill()
monty.goto(-100,-100)
monty.pendown()
monty.forward(200)
monty.left(90)
monty.forward(200)
monty.left(90)
monty.forward(200)
monty.left(90)
monty.forward(200)
monty.right(180)
monty.forward(100)
monty.right(90)
monty.forward(100)
monty.circle(100)
monty.end_fill()
